import Image from "next/image";
import Link from "next/link";
import { ArrowDownIcon, ArrowRightIcon, ArrowUpRightIcon, CalendarDaysIcon, MapPinIcon } from "@heroicons/react/24/outline";
import { BannerReveal } from "@/components/banner-reveal";
import { Container } from "@/components/container";
import { FAQList } from "@/components/faq-list";
import { SectionHeading } from "@/components/section-heading";
import { divisions, faqs, siteConfig } from "@/lib/content";

export default function HomeContent() {
  return <>
    <section className="relative isolate min-h-[calc(100svh-76px)] overflow-hidden bg-night text-white">
      <div className="absolute inset-0 halloween-grid opacity-40" aria-hidden="true" />
      <div className="absolute -right-40 top-[-6rem] h-[34rem] w-[34rem] rounded-full border border-halloween/20 sm:right-[-8rem] sm:top-[-8rem] sm:h-[48rem] sm:w-[48rem]" aria-hidden="true"><div className="absolute inset-8 rounded-full border border-halloween/20" /><div className="absolute inset-20 rounded-full border border-white/10" /></div>
      <Container className="relative grid min-h-[calc(100svh-76px)] content-between gap-12 py-8 sm:py-12">
        <div className="flex flex-wrap items-center justify-between gap-4 text-[11px] font-bold uppercase tracking-[.2em] text-white/65 sm:text-xs"><span>{siteConfig.institution}</span><span className="inline-flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-halloween" /> MGIT · HYDERABAD</span></div>
        <div className="grid items-center gap-9 lg:grid-cols-[1fr_15rem]">
          <div className="relative z-10">
            <p className="mb-6 inline-flex -rotate-2 items-center gap-2 border border-halloween bg-halloween px-4 py-2 text-xs font-black uppercase tracking-[.14em] text-night"><span aria-hidden="true">✦</span> A Halloween special</p>
            <h1 className="font-display text-[clamp(4.7rem,14vw,12rem)] font-black uppercase leading-[.74] tracking-[-.085em]">TECH<span className="text-halloween">KRITI</span><br/><span className="text-outline">AFTER</span><br/>DARK<span className="text-halloween">.</span></h1>
            <p className="mt-8 max-w-xl text-lg leading-relaxed text-white/70 sm:text-xl">Two October nights. One campus after dark. A Halloween celebration from the Department of IT and CSBS at MGIT.</p>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/events" className="group inline-flex items-center gap-3 bg-halloween px-6 py-4 font-black uppercase tracking-wider text-night transition hover:bg-white focus:outline-none focus-visible:ring-4 focus-visible:ring-white">Explore the lineup <ArrowRightIcon className="h-5 w-5 transition-transform group-hover:translate-x-1" /></Link><a href="#reveal-title" className="inline-flex items-center gap-2 border border-white/30 px-5 py-4 font-bold uppercase tracking-wider text-white hover:border-halloween hover:text-halloween focus:outline-none focus-visible:ring-4 focus-visible:ring-halloween">See the reveal <ArrowDownIcon className="h-4 w-4" /></a></div>
          </div>
          <div className="relative mx-auto hidden w-full max-w-[18rem] lg:block"><div className="absolute -inset-4 rotate-3 border border-halloween/50" /><div className="relative aspect-square overflow-hidden border-4 border-white bg-white p-2"><Image src="/fest-logo.jpeg" alt="Full Techkriti Halloween emblem, including the spiderweb, spider and pumpkin" fill sizes="288px" className="object-contain" fetchPriority="high" /></div><p className="mt-4 text-center font-mono text-xs uppercase tracking-[.2em] text-halloween">MGIT · 2026</p></div>
        </div>
        <div className="flex flex-wrap gap-x-12 gap-y-5 border-t border-white/15 pt-6 text-sm"><div className="inline-flex items-center gap-3"><CalendarDaysIcon className="h-5 w-5 text-halloween" /><span className="font-bold">16—17 OCTOBER 2026</span></div><div className="inline-flex items-center gap-3"><MapPinIcon className="h-5 w-5 text-halloween" /><span className="font-bold">MGIT · HYDERABAD</span></div></div>
      </Container>
      <div className="overflow-hidden border-t border-white/15 bg-halloween py-3 text-night" aria-hidden="true"><div className="marquee-track flex w-max gap-8 font-display text-lg font-black uppercase tracking-wide"><span>TECHKRITI AFTER DARK ✳ BUILD BY DAY — HAUNT BY NIGHT ✳ 16—17 OCTOBER ✳ </span><span>TECHKRITI AFTER DARK ✳ BUILD BY DAY — HAUNT BY NIGHT ✳ 16—17 OCTOBER ✳ </span></div></div>
    </section>

    <section className="py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><SectionHeading kicker="The night shift begins" title="A little eerie. A lot of energy." /><p className="max-w-2xl text-lg leading-relaxed text-ink/70">The familiar MGIT campus gets a Halloween transformation for two nights of student-run events, surprises and a full campus atmosphere. The event lineup and room assignments are being finalized; this site will grow as details are confirmed.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{divisions.map((division, index) => <Link key={division} href={`/events?division=${encodeURIComponent(division)}`} className="group relative min-h-[21rem] overflow-hidden border border-ink bg-night p-7 text-white transition-transform hover:-translate-y-1 focus:outline-none focus-visible:ring-4 focus-visible:ring-halloween sm:p-9"><div className="absolute -right-12 -top-12 h-56 w-56 rounded-full border border-halloween/30 transition-transform group-hover:scale-110"><div className="absolute inset-7 rounded-full border border-white/10" /></div><p className="text-xs font-bold uppercase tracking-[.22em] text-halloween">0{index + 1} / The lineup</p><h3 className="relative mt-24 font-display text-4xl font-black uppercase leading-[.88] tracking-tight sm:text-5xl">{division}<br/><span className="text-white/40">EVENTS</span></h3><div className="relative mt-5 flex items-center justify-between border-t border-white/20 pt-4"><p className="text-sm text-white/60">Names and details coming soon</p><ArrowUpRightIcon className="h-6 w-6 text-halloween transition-transform group-hover:rotate-12" /></div></Link>)}</div></Container></section>

    <BannerReveal />

    <section className="bg-[#ede2d6] py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading kicker="Mark the nights" title="The campus after dark." copy="Put the dates aside. More event times and room numbers will be added when confirmed." /><div className="mt-8 inline-flex items-center gap-3 border border-ink bg-paper px-5 py-4 font-display text-xl font-black"><CalendarDaysIcon className="h-6 w-6 text-halloween" /> 16—17 OCT · MGIT</div></div><div className="grid gap-5">{["FRIDAY · 16 OCTOBER", "SATURDAY · 17 OCTOBER"].map((day, index) => <div key={day} className="flex min-h-36 items-center justify-between border border-ink bg-paper p-6 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-halloween">Hyderabad · MGIT campus</p><h3 className="mt-3 font-display text-2xl font-black sm:text-3xl">{day}</h3></div><span className="font-display text-6xl font-black text-ink/10 sm:text-7xl">0{index + 1}</span></div>)}<Link href="/schedule" className="flex items-center justify-between border border-ink bg-night p-5 font-bold text-white transition hover:bg-halloween hover:text-night">See schedule updates <ArrowRightIcon className="h-5 w-5" /></Link></div></div></Container></section>

    <section className="py-20 sm:py-28"><Container><SectionHeading kicker="Good to know" title="A few things before the night." /><div className="mt-10"><FAQList items={faqs.slice(0,4)} /></div><Link href="/faq" className="mt-7 inline-flex font-bold underline decoration-halloween decoration-2 underline-offset-8">All the details</Link></Container></section>

    <section className="relative overflow-hidden bg-halloween py-20 text-night sm:py-24"><div className="absolute inset-0 opacity-20 halloween-grid" aria-hidden="true" /><Container className="relative flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-end"><div><p className="font-bold uppercase tracking-[.2em]">Two dates to remember</p><h2 className="mt-4 max-w-4xl font-display text-5xl font-black uppercase leading-[.88] tracking-[-.04em] sm:text-7xl">Meet us after dark.</h2><p className="mt-5 text-lg font-medium">16—17 October · MGIT, Hyderabad</p></div><Link href="/events" className="shrink-0 border border-night bg-night px-7 py-5 font-bold uppercase tracking-wider text-white transition hover:bg-white hover:text-night">Explore event updates</Link></Container></section>
  </>;
}
