import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, ArrowUpRightIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { BannerReveal } from "@/components/banner-reveal";
import { Container } from "@/components/container";
import { EventCard } from "@/components/event-card";
import { FAQList } from "@/components/faq-list";
import { PreviousEditionPreview } from "@/components/previous-edition-preview";
import { events, faqs } from "@/lib/content";

const featured = events.filter((event) => event.featured);
const visibleEvents = (featured.length ? featured : events).slice(0, 3);

export default function HomeStory() {
  return <>
    <section className="relative isolate overflow-hidden border-b border-[#6f465b] bg-[#0b0710]">
      <Image src="/hero-halloween.png" alt="" fill sizes="100vw" quality={80} fetchPriority="high" className="object-cover object-[68%_center] opacity-65" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#0b0710] via-[#0b0710]/90 to-[#0b0710]/25" aria-hidden="true" />
      <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-[#0b0710] to-transparent" aria-hidden="true" />
      <Container className="relative z-10 flex min-h-[560px] flex-col justify-between py-10 sm:min-h-[610px] sm:py-12">
        <p className="text-xs font-bold uppercase tracking-[.2em] text-[#ffaf79]">MGIT · IT & CSBS · 16—17 OCTOBER 2026</p>
        <div className="max-w-3xl py-16 sm:py-20">
          <p className="eyebrow">A HALLOWEEN-THEMED CAMPUS FESTIVAL</p>
          <h1 className="mt-5 max-w-3xl font-display text-[clamp(3.4rem,8vw,7.5rem)] font-black leading-[.9] tracking-[-.07em] text-[#fff1df]">Techkriti is <span className="font-haunt font-normal italic text-[#ff914d]">ours to make.</span></h1>
          <p className="mt-7 max-w-2xl text-lg leading-relaxed text-[#f0d8ca] sm:text-xl">Two days at MGIT to explore technical challenges, enjoy non-technical experiences, and make something memorable together. This year, the campus wears a Halloween glow.</p>
          <div className="mt-9 flex flex-wrap gap-3"><a href="#discover" className="button-flame inline-flex min-h-12 items-center gap-3 px-6 py-3 text-sm font-black uppercase tracking-[.12em] text-[#170c14] focus:outline-none focus-visible:ring-4 focus-visible:ring-white">Find your event <ArrowRightIcon className="h-5 w-5" /></a><a href="#about-techkriti" className="inline-flex min-h-12 items-center gap-3 border border-[#d5ad9e] bg-[#0b0710]/50 px-6 py-3 text-sm font-bold uppercase tracking-[.12em] text-[#fff1df] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d]">What is Techkriti?</a></div>
        </div>
        <div className="flex flex-wrap gap-x-12 gap-y-3 border-t border-[#f7c9aa]/35 pt-5 text-xs font-bold uppercase tracking-[.16em] text-[#f4d9c5]"><span>16—17 October 2026</span><span>MGIT, Hyderabad</span><span>Technical + non-technical</span></div>
      </Container>
    </section>

    <section id="discover" aria-labelledby="discover-title" className="scroll-mt-20 bg-[#f7efe5] py-16 text-[#261625] sm:py-20"><Container><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#9c441e]">01 / FIND YOUR PLACE</p><h2 id="discover-title" className="mt-3 max-w-2xl font-display text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-6xl">Start with an event that feels like you.</h2></div><p className="max-w-md leading-relaxed text-[#5f4c5d]">Search by name or interest, choose a track, or look at a festival day. When entries are confirmed, every event will have its own details and registration link.</p></div>
      <form action="/events" method="get" role="search" className="mt-9 grid gap-4 border border-[#ceb9ba] bg-white p-5 shadow-[0_12px_35px_#29162a12] sm:grid-cols-2 lg:grid-cols-[1.6fr_1fr_1fr_auto] lg:items-end lg:p-6">
        <label className="grid gap-2 text-xs font-black uppercase tracking-[.14em] text-[#6c3450]">Search events<div className="relative"><MagnifyingGlassIcon className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#744f61]" aria-hidden="true" /><input name="q" type="search" placeholder="Event name or interest" className="min-h-12 w-full border border-[#c7aeb7] bg-[#fffaf5] py-3 pl-11 pr-4 text-base font-normal normal-case tracking-normal text-[#261625] placeholder:text-[#7b6475] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d]" /></div></label>
        <label className="grid gap-2 text-xs font-black uppercase tracking-[.14em] text-[#6c3450]">Track<select name="division" defaultValue="" className="min-h-12 border border-[#c7aeb7] bg-[#fffaf5] px-3 text-base font-normal normal-case tracking-normal text-[#261625] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d]"><option value="">All tracks</option><option value="Technical">Technical</option><option value="Non-Technical">Non-technical</option></select></label>
        <label className="grid gap-2 text-xs font-black uppercase tracking-[.14em] text-[#6c3450]">Day<select name="day" defaultValue="" className="min-h-12 border border-[#c7aeb7] bg-[#fffaf5] px-3 text-base font-normal normal-case tracking-normal text-[#261625] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d]"><option value="">Both days</option><option value="1">16 October</option><option value="2">17 October</option></select></label>
        <button type="submit" className="min-h-12 bg-[#261625] px-6 py-3 text-sm font-black uppercase tracking-[.12em] text-white hover:bg-[#6b3150] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d]">Search events</button>
      </form>
      {visibleEvents.length ? <><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visibleEvents.map((event) => <EventCard key={event.slug} event={event} />)}</div><Link href="/events" className="mt-8 inline-flex items-center gap-2 font-bold text-[#7c3218] underline decoration-2 underline-offset-4">See all events <ArrowRightIcon className="h-5 w-5" /></Link></> : <div className="mt-6 flex flex-col justify-between gap-5 border-l-4 border-[#f07a36] bg-[#fffaf5] px-6 py-5 sm:flex-row sm:items-center"><div><p className="text-lg font-black">The 2026 lineup is being confirmed.</p><p className="mt-1 text-[#665266]">Event names, rules, rooms and Google Form links will be added as soon as organizers finalize them.</p></div><Link href="/events" className="inline-flex shrink-0 items-center gap-2 font-bold text-[#7c3218] underline decoration-2 underline-offset-4">View the event page <ArrowUpRightIcon className="h-5 w-5" /></Link></div>}
    </Container></section>

    <section id="about-techkriti" aria-labelledby="about-title" className="scroll-mt-20 border-b border-[#704a60] bg-[#130c18] py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="eyebrow">02 / THE IDEA</p><h2 id="about-title" className="mt-5 font-haunt text-5xl leading-[1.05] text-[#fff0dc] sm:text-7xl">What is <em className="text-[#ff914d]">Techkriti?</em></h2></div><div className="lg:pt-8"><p className="text-xl leading-relaxed text-[#f3dfd0] sm:text-2xl">It is a place to try things, meet people, and take pride in what our campus can create together.</p><p className="mt-6 max-w-2xl leading-relaxed text-[#c5b2be]">Presented by MGIT’s Department of IT and CSBS, Techkriti brings technical and non-technical experiences into one festival. The Halloween theme gives this year its atmosphere; the people who participate give it its energy.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-bold uppercase tracking-[.12em] text-[#ffad78] underline decoration-[#ff914d] underline-offset-8">More about Techkriti <ArrowRightIcon className="h-5 w-5" /></Link></div></div>
      <div className="mt-14 grid gap-5 md:grid-cols-2"><Link href="/events?division=Technical" className="group border border-[#79506c] bg-[#201327] p-7 focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d] sm:p-9"><span className="eyebrow">THE TECHNICAL TRACK</span><h3 className="mt-5 font-haunt text-4xl text-[#fff0dc] sm:text-5xl">Think. Test. Build.</h3><p className="mt-4 max-w-md leading-relaxed text-[#c5b2be]">A space for curiosity and problem-solving. Confirmed technical events will be listed here with the details you need to participate.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-[#ffad78] group-hover:text-white">Explore technical events <ArrowUpRightIcon className="h-5 w-5" /></span></Link><Link href="/events?division=Non-Technical" className="group border border-[#79506c] bg-[#291820] p-7 focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff914d] sm:p-9"><span className="eyebrow">THE NON-TECHNICAL TRACK</span><h3 className="mt-5 font-haunt text-4xl text-[#fff0dc] sm:text-5xl">Create. Play. Connect.</h3><p className="mt-4 max-w-md leading-relaxed text-[#c5b2be]">There is more than one way to be part of Techkriti. Confirmed non-technical events will appear here as the lineup takes shape.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-[#ffad78] group-hover:text-white">Explore non-technical events <ArrowUpRightIcon className="h-5 w-5" /></span></Link></div>
    </Container></section>

    <PreviousEditionPreview />

    <section aria-labelledby="join-title" className="bg-[#f7efe5] py-20 text-[#261625] sm:py-28"><Container><div className="grid gap-7 lg:grid-cols-[.75fr_1.25fr] lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#9c441e]">03 / YOUR PART IN THE STORY</p><h2 id="join-title" className="mt-5 font-display text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-6xl">This fest becomes ours when we show up.</h2><p className="mt-6 max-w-md leading-relaxed text-[#5f4c5d]">Bring your curiosity, your friends, and your ideas. Whether you come for a challenge or a new experience, participating is what makes Techkriti feel like Techkriti.</p></div><ol className="border-t border-[#cbb5bb]"><li className="grid grid-cols-[3rem_1fr] gap-4 border-b border-[#cbb5bb] py-6 sm:grid-cols-[4rem_1fr]"><span className="font-haunt text-3xl italic text-[#ac4e25]">01</span><div><h3 className="text-xl font-black">Explore what interests you</h3><p className="mt-1 leading-relaxed text-[#5f4c5d]">Browse the technical and non-technical tracks, then check each confirmed event’s details.</p></div></li><li className="grid grid-cols-[3rem_1fr] gap-4 border-b border-[#cbb5bb] py-6 sm:grid-cols-[4rem_1fr]"><span className="font-haunt text-3xl italic text-[#ac4e25]">02</span><div><h3 className="text-xl font-black">Register directly</h3><p className="mt-1 leading-relaxed text-[#5f4c5d]">Once forms are published, Register Now takes you to that event’s official Google Form.</p></div></li><li className="grid grid-cols-[3rem_1fr] gap-4 border-b border-[#cbb5bb] py-6 sm:grid-cols-[4rem_1fr]"><span className="font-haunt text-3xl italic text-[#ac4e25]">03</span><div><h3 className="text-xl font-black">Make the campus yours</h3><p className="mt-1 leading-relaxed text-[#5f4c5d]">Come to MGIT on 16–17 October, take part, and help create the energy everyone remembers.</p></div></li></ol></div></Container></section>

    <section aria-labelledby="dates-title" className="border-y border-[#704a60] bg-[#130c18] py-20 sm:py-24"><Container><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">04 / SAVE THE DATES</p><h2 id="dates-title" className="mt-4 font-haunt text-5xl text-[#fff0dc] sm:text-6xl">Two days at MGIT.</h2></div><Link href="/schedule" className="inline-flex items-center gap-2 font-bold text-[#ffad78] underline decoration-[#ff914d] underline-offset-8">See schedule updates <ArrowRightIcon className="h-5 w-5" /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="flex items-center gap-5 border border-[#79506c] bg-[#201327] p-6"><span className="font-haunt text-6xl italic text-[#ff914d]">16</span><div><p className="eyebrow">FRIDAY · OCTOBER</p><p className="mt-2 text-lg font-bold text-[#fff0dc]">Day one at MGIT</p><p className="mt-1 text-sm text-[#c5b2be]">Times and rooms coming soon</p></div></div><div className="flex items-center gap-5 border border-[#79506c] bg-[#201327] p-6"><span className="font-haunt text-6xl italic text-[#ff914d]">17</span><div><p className="eyebrow">SATURDAY · OCTOBER</p><p className="mt-2 text-lg font-bold text-[#fff0dc]">Day two at MGIT</p><p className="mt-1 text-sm text-[#c5b2be]">Times and rooms coming soon</p></div></div></div></Container></section>

    <BannerReveal />

    <section className="bg-[#0b0710] py-20 sm:py-24"><Container><div className="grid gap-9 lg:grid-cols-[.65fr_1fr]"><div><p className="eyebrow">05 / GOOD TO KNOW</p><h2 className="mt-4 font-haunt text-5xl text-[#fff0dc] sm:text-6xl">Before you arrive.</h2><Link href="/faq" className="mt-7 inline-flex items-center gap-2 font-bold text-[#ffad78] underline decoration-[#ff914d] underline-offset-8">All FAQs <ArrowRightIcon className="h-5 w-5" /></Link></div><FAQList items={faqs.slice(0, 4)} /></div></Container></section>

    <section className="border-t border-[#79506c] bg-[#261525] py-16 sm:py-20"><Container className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">TECHKRITI 2026 · MGIT</p><h2 className="mt-4 max-w-3xl font-haunt text-5xl leading-[1.02] text-[#fff0dc] sm:text-7xl">Bring your people. <em className="text-[#ff914d]">Bring your spark.</em></h2><p className="mt-5 text-[#dbc6d0]">We’ll see you on 16–17 October.</p></div><Link href="/events" className="button-flame inline-flex shrink-0 items-center gap-3 self-start px-7 py-4 text-sm font-black uppercase tracking-[.12em] text-[#170c14] focus:outline-none focus-visible:ring-4 focus-visible:ring-white">Explore events <ArrowUpRightIcon className="h-5 w-5" /></Link></Container></section>
  </>;
}
