import Image from "next/image";
import Link from "next/link";
import { ArrowDownIcon, ArrowRightIcon, ArrowUpRightIcon } from "@heroicons/react/24/outline";
import { BannerReveal } from "@/components/banner-reveal";
import { Container } from "@/components/container";
import { FAQList } from "@/components/faq-list";
import { faqs } from "@/lib/content";

export default function HomeExperience() {
  return <>
    <section className="hero-night relative isolate flex min-h-[min(860px,calc(100svh-80px))] overflow-hidden border-b border-orange-500/30 text-[#fff0dc]">
      <Image src="/hero-halloween.png" alt="" fill sizes="100vw" quality={85} fetchPriority="high" className="hero-art object-cover object-[65%_center]" />
      <div className="hero-veil absolute inset-0" aria-hidden="true" />
      <Container className="relative z-10 flex flex-col justify-between pb-8 pt-7 sm:pb-12 sm:pt-10">
        <div className="flex flex-wrap items-center justify-between gap-3 text-[10px] font-bold uppercase tracking-[.24em] text-[#e8c8ac] sm:text-xs">
          <span className="flex items-center gap-3"><span className="h-px w-8 bg-[#ff7431]" /> IT & CSBS PRESENTS</span>
          <span>MGIT · HYDERABAD</span>
        </div>
        <div className="my-20 max-w-[800px] sm:my-28 lg:my-20">
          <p className="mb-5 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.26em] text-[#ff985a] sm:text-sm"><span className="text-lg" aria-hidden="true">✦</span> ENTER IF YOU DARE</p>
          <h1 className="hero-title text-balance font-display font-black uppercase leading-[.76] tracking-[-.08em]">
            <span className="block text-[clamp(3.3rem,11.8vw,10.5rem)]">TECH<span className="text-[#ff762d]">KRITI</span></span>
            <span className="mt-3 block font-haunt text-[clamp(3.6rem,9vw,8rem)] font-normal italic tracking-[-.055em] text-[#ffe8c7] sm:mt-5">After Dark<span className="text-[#ff762d]">.</span></span>
          </h1>
          <div className="mt-7 max-w-xl border-l-2 border-[#ff762d] pl-5 sm:mt-10"><p className="text-lg leading-relaxed text-[#f6dcc7] sm:text-xl">The campus you know. A night you won’t forget. Two days of technical and non-technical experiences, dressed for Halloween.</p></div>
          <div className="mt-8 flex flex-wrap gap-3 sm:mt-10"><Link href="/events" className="button-flame group inline-flex min-h-14 items-center gap-5 px-6 py-4 text-sm font-black uppercase tracking-[.14em] text-[#170c14] focus:outline-none focus-visible:ring-4 focus-visible:ring-white">Explore the event tracks <ArrowUpRightIcon className="h-5 w-5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link><a href="#reveal-title" className="inline-flex min-h-14 items-center gap-3 border border-[#fbd5b7]/50 bg-black/30 px-6 py-4 text-sm font-bold uppercase tracking-[.12em] text-[#fff0dc] backdrop-blur-sm transition hover:border-[#ff762d] hover:text-[#ff9a61] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff762d]">The banner reveal <ArrowDownIcon className="h-4 w-4" /></a></div>
        </div>
        <div className="grid gap-5 border-t border-[#f8c7a3]/35 pt-6 text-sm font-bold uppercase tracking-[.18em] text-[#fff0dc] sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><span className="mb-2 block text-[10px] text-[#ff985a]">WHEN THE NIGHT BEGINS</span>16—17 OCTOBER 2026</div><div><span className="mb-2 block text-[10px] text-[#ff985a]">WHERE TO FIND US</span>MGIT · HYDERABAD</div><span className="hidden text-4xl text-[#ff762d] sm:block" aria-hidden="true">✦</span></div>
      </Container>
    </section>

    <div className="night-ribbon overflow-hidden border-b border-[#ff762d]/30 py-3 text-[#ffb175]" aria-hidden="true"><div className="marquee-track flex w-max gap-8 font-haunt text-xl italic tracking-[.08em] sm:text-2xl"><span>✦ TECHKRITI AFTER DARK ✦ TWO DAYS, ONE HAUNTED CAMPUS ✦ OCTOBER 16—17 ✦ </span><span>✦ TECHKRITI AFTER DARK ✦ TWO DAYS, ONE HAUNTED CAMPUS ✦ OCTOBER 16—17 ✦ </span></div></div>

    <section className="relative overflow-hidden py-24 sm:py-32"><div className="ambient-glow pointer-events-none absolute -right-40 top-0 h-[34rem] w-[34rem]" aria-hidden="true" /><Container className="relative"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="eyebrow">01 / THE FESTIVAL</p><h2 className="mt-5 font-haunt text-5xl leading-[1.05] text-[#fff0dc] sm:text-7xl">Something is <em className="text-[#ff7834]">brewing.</em></h2></div><p className="max-w-2xl text-lg leading-relaxed text-[#c4adbd] sm:text-xl">For two days, MGIT becomes a different kind of playground. Techkriti brings the Department of IT and CSBS together for technical challenges, non-technical fun, and a Halloween atmosphere all its own. The official lineup is still under wraps.</p></div>
      <div className="mt-16 grid gap-5 md:grid-cols-2">
        <Link href="/events?division=Technical" className="track-card track-card-tech group relative flex min-h-[390px] flex-col justify-between overflow-hidden border border-[#79506c] p-7 transition-transform motion-safe:hover:-translate-y-1 focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff7834] sm:p-9"><div className="track-symbol" aria-hidden="true">⌘</div><div className="relative flex items-start justify-between"><span className="eyebrow">THE FIRST PATH / 01</span><ArrowUpRightIcon className="h-6 w-6 text-[#ff985a] transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div className="relative"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#ff985a]">WITS. SKILL. CURIOSITY.</p><h3 className="font-haunt text-5xl leading-none text-[#fff0dc] sm:text-6xl">Technical<br/><em>events</em></h3><p className="mt-6 border-t border-white/20 pt-5 text-sm text-[#cdb5c9]">Names, rules and rooms will appear when confirmed.</p></div></Link>
        <Link href="/events?division=Non-Technical" className="track-card track-card-play group relative flex min-h-[390px] flex-col justify-between overflow-hidden border border-[#79506c] p-7 transition-transform motion-safe:hover:-translate-y-1 focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff7834] sm:p-9"><div className="track-symbol" aria-hidden="true">✳</div><div className="relative flex items-start justify-between"><span className="eyebrow">THE SECOND PATH / 02</span><ArrowUpRightIcon className="h-6 w-6 text-[#ff985a] transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div className="relative"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#ff985a]">PLAY. CREATE. SURPRISE.</p><h3 className="font-haunt text-5xl leading-none text-[#fff0dc] sm:text-6xl">Non-technical<br/><em>events</em></h3><p className="mt-6 border-t border-white/20 pt-5 text-sm text-[#cdb5c9]">Names, rules and rooms will appear when confirmed.</p></div></Link>
      </div></Container></section>

    <BannerReveal />

    <section className="relative overflow-hidden border-y border-[#6b3a41]/40 bg-[#130b18] py-24 sm:py-32"><Container><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">02 / MARK THE DATES</p><h2 className="mt-5 font-haunt text-5xl leading-[1.05] text-[#fff0dc] sm:text-7xl">Two days.<br/><em className="text-[#ff7834]">One spell.</em></h2><p className="mt-7 max-w-sm leading-relaxed text-[#c4adbd]">The event-by-event timings and MGIT room numbers will be posted as soon as they are final.</p><Link href="/schedule" className="mt-8 inline-flex items-center gap-3 border-b border-[#ff7834] pb-2 text-sm font-bold uppercase tracking-[.16em] text-[#ff9d65] transition hover:text-white focus:outline-none focus-visible:ring-4 focus-visible:ring-[#ff7834]">View the schedule <ArrowRightIcon className="h-5 w-5" /></Link></div><div className="night-calendar"><div className="calendar-row"><span className="calendar-date">16</span><div><span className="eyebrow">FRIDAY / DAY ONE</span><h3 className="mt-2 font-haunt text-3xl text-[#fff0dc] sm:text-4xl">October begins after dark</h3><p className="mt-2 text-[#bba4b7]">MGIT campus · venues to be announced</p></div></div><div className="calendar-row"><span className="calendar-date">17</span><div><span className="eyebrow">SATURDAY / DAY TWO</span><h3 className="mt-2 font-haunt text-3xl text-[#fff0dc] sm:text-4xl">The night continues</h3><p className="mt-2 text-[#bba4b7]">MGIT campus · venues to be announced</p></div></div></div></div></Container></section>

    <section className="py-24 sm:py-32"><Container><div className="grid gap-8 lg:grid-cols-[.6fr_1fr]"><div><p className="eyebrow">03 / BEFORE YOU ARRIVE</p><h2 className="mt-5 font-haunt text-5xl text-[#fff0dc] sm:text-6xl">Questions from<br/><em className="text-[#ff7834]">the shadows.</em></h2><Link href="/faq" className="mt-8 inline-flex items-center gap-3 text-sm font-bold uppercase tracking-[.15em] text-[#ff9d65] hover:text-white">All FAQs <ArrowRightIcon className="h-5 w-5" /></Link></div><FAQList items={faqs.slice(0, 4)} /></div></Container></section>

    <section className="final-invite relative overflow-hidden border-t border-[#ff7834]/30 py-24 sm:py-32"><Container className="relative z-10"><p className="eyebrow">YOUR INVITATION IS WAITING</p><h2 className="mt-5 max-w-5xl font-haunt text-6xl leading-[.98] text-[#fff0dc] sm:text-8xl">See you on the <em className="text-[#ff7834]">other side.</em></h2><div className="mt-10 flex flex-wrap items-center gap-8"><Link href="/events" className="button-flame inline-flex items-center gap-5 px-7 py-4 text-sm font-black uppercase tracking-[.14em] text-[#170c14] focus:outline-none focus-visible:ring-4 focus-visible:ring-white">Explore the lineup <ArrowUpRightIcon className="h-5 w-5" /></Link><p className="text-sm font-bold uppercase tracking-[.18em] text-[#d4b2a3]">16—17 OCTOBER · MGIT</p></div></Container></section>
  </>;
}
