import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, ArrowUpRightIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { BannerReveal } from "@/components/banner-reveal";
import { Container } from "@/components/container";
import { EventCarousel } from "@/components/event-carousel";
import { FAQList } from "@/components/faq-list";
import { archivePhotos } from "@/lib/archive";
import { events, faqs } from "@/lib/content";

export default function HomeRebuilt() {
  return <>
    <section className="relative isolate overflow-hidden bg-[#170f1b] text-[#fff6e9]">
      <Image src="/hero-halloween.webp" alt="" fill sizes="100vw" fetchPriority="high" className="object-cover object-[68%_center] sm:object-[72%_center]" />
      <div className="festival-hero-veil absolute inset-0" aria-hidden="true" />
      <Container className="relative flex min-h-[430px] flex-col justify-center py-12 sm:min-h-[540px] sm:py-16 lg:min-h-[570px]">
        <p className="eyebrow text-[#ffae7b]">16–17 OCTOBER 2026 · MGIT, HYDERABAD</p>
        <h1 className="mt-5 max-w-5xl font-display text-[clamp(3.1rem,8.2vw,7.7rem)] font-black leading-[.91] tracking-[-.08em]">Techkriti,<br /><span className="text-[#ff985c]">after dark.</span></h1>
        <p className="mt-5 max-w-xl text-base leading-relaxed text-[#f4e4dc] sm:mt-7 sm:text-xl">MGIT’s student festival returns with a Halloween identity and technical and non-technical ways to take part.</p>
        <Link href="#discover" className="button-flame mt-6 inline-flex min-h-12 w-fit items-center gap-3 px-6 py-3 font-extrabold sm:mt-8">Discover events <ArrowRightIcon className="h-5 w-5" /></Link>
      </Container>
    </section>

    <section id="discover" aria-labelledby="discover-title" className="scroll-mt-20 bg-[#f2eee7] py-9 sm:py-16">
      <Container>
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow eyebrow-dark">The event lineup</p><h2 id="discover-title" className="mt-2 max-w-3xl text-[clamp(2rem,4.5vw,4.2rem)] font-black leading-[1.01] tracking-[-.06em] text-[#211521]">Find your place here.</h2></div><Link href="/events" className="text-link hidden shrink-0 items-center gap-2 font-bold text-[#8c381b] sm:inline-flex">All events <ArrowUpRightIcon className="h-5 w-5" /></Link></div>
        {!events.length && <div className="mt-6 grid grid-flow-dense grid-cols-2 gap-2 sm:mt-8 sm:gap-4"><Link href="/events?division=Technical" className="flex min-h-16 items-center justify-between gap-2 border border-[#bcaea8] bg-[#fffaf3] px-4 py-3 font-bold text-[#211521] hover:border-[#a34a28] sm:px-6">Technical <ArrowUpRightIcon className="h-5 w-5 shrink-0 text-[#a34a28]" /></Link><Link href="/events?division=Non-Technical" className="flex min-h-16 items-center justify-between gap-2 border border-[#bcaea8] bg-[#fffaf3] px-4 py-3 font-bold text-[#211521] hover:border-[#a34a28] sm:px-6">Non-technical <ArrowUpRightIcon className="h-5 w-5 shrink-0 text-[#a34a28]" /></Link></div>}
        {events.length > 0 && <form action="/events" method="get" role="search" className="mt-4 flex flex-col gap-2 sm:flex-row"><label htmlFor="home-event-search" className="sr-only">Search events</label><div className="relative flex-1"><MagnifyingGlassIcon aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#775e62]" /><input id="home-event-search" name="q" type="search" placeholder="Search events or interests" className="min-h-12 w-full border border-[#bcaea8] bg-white py-3 pl-11 pr-4 text-[#211521] placeholder:text-[#6f6265]" /></div><button type="submit" className="button-dark min-h-12 px-6 py-3 font-bold">Search events</button></form>}
        {events.length ? <EventCarousel events={events} /> : <div className="mt-5 border-l-4 border-[#e56731] bg-[#e8dfd6] px-5 py-4 sm:px-6"><h3 className="text-lg font-extrabold text-[#211521]">The 2026 lineup is being confirmed.</h3><p className="mt-1 max-w-3xl leading-relaxed text-[#54474a]">Event names, rules, rooms and Google Form links will appear here as organizers finalize them.</p></div>}
        <Link href="/events" className="text-link mt-5 inline-flex items-center gap-2 font-bold text-[#8c381b] sm:hidden">Open the event page <ArrowUpRightIcon className="h-5 w-5" /></Link>
      </Container>
    </section>

    <section aria-labelledby="about-home-title" className="bg-[#241722] py-16 text-[#fff6e9] sm:py-24"><Container className="grid gap-6 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="eyebrow">A festival made here</p><h2 id="about-home-title" className="mt-3 max-w-3xl text-[clamp(2.8rem,5vw,5rem)] font-black leading-[.99] tracking-[-.065em]">What is <span className="font-haunt text-[#ff985c]">Techkriti?</span></h2></div><div><p className="max-w-2xl text-lg leading-relaxed text-[#e4d2cb]">Two days at MGIT for technical and non-technical experiences. This October brings a Halloween identity; everyone who joins helps make the festival their own.</p><Link href="/about" className="text-link mt-6 inline-flex items-center gap-2 font-bold text-[#ffad7a]">Our story <ArrowRightIcon className="h-5 w-5" /></Link></div></Container></section>

    <BannerReveal />

    <section aria-labelledby="expect-title" className="bg-[#f2eee7] py-20 sm:py-28"><Container><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow eyebrow-dark">What to expect</p><h2 id="expect-title" className="mt-4 text-[clamp(2.8rem,5vw,5rem)] font-black leading-[.98] tracking-[-.065em] text-[#211521]">Two days. Two tracks.<br /><span className="font-haunt text-[#a84324]">Your way in.</span></h2></div><Link href="/schedule" className="text-link inline-flex items-center gap-2 font-bold text-[#8c381b]">View schedule updates <ArrowRightIcon className="h-5 w-5" /></Link></div><div className="mt-10 grid gap-3 md:grid-cols-2"><Link href="/events?division=Technical" className="group flex min-h-36 flex-col justify-between border border-[#bcaea8] bg-[#fffaf3] p-6 hover:border-[#a34a28]"><span className="text-xs font-extrabold uppercase tracking-[.17em] text-[#a44622]">01 / A route into the festival</span><span className="flex items-end justify-between gap-4 text-2xl font-black text-[#211521] sm:text-3xl">Technical <ArrowUpRightIcon className="h-6 w-6 shrink-0 text-[#a34a28]" /></span></Link><Link href="/events?division=Non-Technical" className="group flex min-h-36 flex-col justify-between border border-[#bcaea8] bg-[#fffaf3] p-6 hover:border-[#a34a28]"><span className="text-xs font-extrabold uppercase tracking-[.17em] text-[#a44622]">02 / Another way to take part</span><span className="flex items-end justify-between gap-4 text-2xl font-black text-[#211521] sm:text-3xl">Non-technical <ArrowUpRightIcon className="h-6 w-6 shrink-0 text-[#a34a28]" /></span></Link></div><div className="mt-10 border-t border-[#bcaea8]"><div className="grid gap-3 border-b border-[#bcaea8] py-7 sm:grid-cols-[8rem_1fr_auto] sm:items-center"><span className="text-6xl font-black tracking-[-.08em] text-[#c14d25]">16</span><div><h3 className="text-2xl font-bold text-[#211521]">Friday, 16 October</h3><p className="mt-1 text-[#62555a]">MGIT campus · times and rooms to be confirmed</p></div><span className="text-sm font-semibold text-[#65555a]">Day one</span></div><div className="grid gap-3 border-b border-[#bcaea8] py-7 sm:grid-cols-[8rem_1fr_auto] sm:items-center"><span className="text-6xl font-black tracking-[-.08em] text-[#c14d25]">17</span><div><h3 className="text-2xl font-bold text-[#211521]">Saturday, 17 October</h3><p className="mt-1 text-[#62555a]">MGIT campus · times and rooms to be confirmed</p></div><span className="text-sm font-semibold text-[#65555a]">Day two</span></div></div></Container></section>

    <section aria-labelledby="archive-title" className="bg-[#e7dfd4] py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.88fr_1.12fr] lg:items-center"><div><p className="eyebrow eyebrow-dark">From the February 2026 edition</p><h2 id="archive-title" className="mt-4 max-w-xl text-[clamp(2.8rem,5vw,5rem)] font-black leading-[.98] tracking-[-.065em] text-[#211521]">Before this chapter, <span className="font-haunt text-[#a84324]">there was us.</span></h2><p className="mt-6 max-w-lg text-lg leading-relaxed text-[#514448]">These are real moments from the previous Techkriti, when students filled the campus with their own ideas and energy. October’s Halloween edition will be a new story.</p><Link href="/gallery" className="text-link mt-7 inline-flex items-center gap-2 font-bold text-[#8c381b]">See the February photo gallery <ArrowRightIcon className="h-5 w-5" /></Link></div><div className="grid grid-cols-2 gap-2 sm:gap-3"><figure className="col-span-2"><div className="archive-image relative aspect-[1.7] overflow-hidden bg-[#cabcb1]"><Image src={archivePhotos[0].src} alt={archivePhotos[0].alt} fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover" /></div><figcaption className="mt-2 text-xs font-semibold text-[#65555a]">February 2026 · {archivePhotos[0].caption}</figcaption></figure>{archivePhotos.slice(1, 3).map((photo) => <figure key={photo.src}><div className="archive-image relative aspect-[1.1] overflow-hidden bg-[#cabcb1]"><Image src={photo.src} alt={photo.alt} fill sizes="(max-width: 1024px) 50vw, 28vw" className="object-cover" /></div></figure>)}</div></div></Container></section>

    <section className="bg-[#f2eee7] py-20 sm:py-28"><Container className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow eyebrow-dark">Good to know</p><h2 className="mt-4 text-5xl font-black leading-none tracking-[-.06em] text-[#211521] sm:text-6xl">Questions<br />before you go?</h2><Link href="/faq" className="text-link mt-7 inline-flex items-center gap-2 font-bold text-[#8c381b]">See all FAQs <ArrowRightIcon className="h-5 w-5" /></Link></div><FAQList items={faqs.slice(0, 4)} /></Container></section>

    <section className="bg-[#f47736] py-16 text-[#211521] sm:py-20"><Container className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]">16–17 October 2026 · MGIT</p><h2 className="mt-4 max-w-4xl text-[clamp(2.8rem,5.5vw,5.5rem)] font-black leading-[.96] tracking-[-.07em]">Find what you want to be part of.</h2></div><Link href="/events" className="button-dark inline-flex min-h-12 shrink-0 items-center gap-3 self-start px-7 py-4 font-extrabold">Explore events <ArrowUpRightIcon className="h-5 w-5" /></Link></Container></section>
  </>;
}
